# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-28 01:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='property.Property'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('done', 'Done'), ('cancelled', 'Cancelled')], max_length=35),
        ),
        migrations.AlterField(
            model_name='survey',
            name='activity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='activity.Activity'),
        ),
    ]
